# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrenchVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=40)),
                ('french', models.CharField(max_length=40)),
                ('french_ascii', models.CharField(max_length=40)),
            ],
        ),
    ]
