# Generated by Django 3.2.4 on 2021-06-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frenchverb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
